### ISSUE TITLE
Site shows tons of JavaScript gibberish on Netscape 1.12 on MacOS

### ISSUE THREAD

**Issue by jonthysell** [ActionRetro/68k-news#5]
I can get to the site, but every page shows a bunch of javascript at the top.

![20210505_103256](https://user-images.githubusercontent.com/10852185/117184646-cca08d00-ad8d-11eb-8139-14d6e6e4439d.jpg)

**Comment by ActionRetro** [comment]
This was a bug from the hosting company, which decided to add New Relic to the site as a "feature" - thanks for alerting me!!
