### ISSUE TITLE
Site causes Netscape 2.02 on MacOS to crash when JavaScript is enabled

### ISSUE THREAD

**Issue by jonthysell** [ActionRetro/68k-news#6]
I know it says you've tested on Netscape 1-4 on an SE/30.

I'm on an SE/30 running 7.5.5, and using Netscape 2.02 I keep getting a JavaScript alert (multiple times) that eventually causes the whole app to crash.

Disabling JS and everything of course works fine. I don't mind turning JS off, just checking that that's the expected behavior.

![20210505_112941](https://user-images.githubusercontent.com/10852185/117191686-b3034380-ad95-11eb-9c93-6dc6acf59785.jpg)

**Comment by ActionRetro** [comment]
This was a bug from the hosting company, which decided to add New Relic to the site as a "feature" - thanks for alerting me!!
